# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

footer: 'reach out via <a href="https://www.linkedin.com/in/pavlotsyhanok/">LinkedIn</a>'

#style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

csp:
  frame-src: "'self' http://www.youtube.com https://www.youtube.com https://*"
